/*
 * BookIntroduce.java
 *
 * Created on __DATE__, __TIME__
 */

package novel;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

/**
 * 
 * @author __USER__
 */
@SuppressWarnings("serial")
public class BookIntroduce extends javax.swing.JFrame {

	static String nickname = null;
	static String bookname = null;
	static int id = 0;
	int i =0;

	/** Creates new form BookIntroduce */
	@SuppressWarnings("static-access")
	public BookIntroduce(String nickname, String bookname,int id) {
		this.nickname = nickname;
		this.bookname = bookname;
		this.id = id;
		initComponents(nickname, bookname, id);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	public void initComponents(final String nickname, final String bookname,final int id) {

		this.setTitle("内容简介");
		this.setResizable(false);
		jLabel3 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		jLabel21 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jLabel22 = new javax.swing.JLabel();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();

		jButton1.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				try {
					if (nickname==null) {
						JOptionPane.showMessageDialog(null, "请先进行登陆");
						new NovelLogin().setVisible(true);
						dispose();
						return;
					}
					Client c = new Client();
					@SuppressWarnings("unused")
					User u = c.mark(nickname, bookname);
				} catch (IOException e1) {
					e1.printStackTrace();
				} catch (ClassNotFoundException e2) {
					e2.printStackTrace();
				}
			}
		});

		jLabel3.setText("jLabel3");

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(171, 156, 137));

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 36));
		jLabel1.setForeground(new java.awt.Color(102, 102, 102));
		jLabel1.setText("\u4e09\u56fd\u6f14\u4e49");

		jLabel2.setBackground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("                   \u5c01\u9762");
		jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(
				javax.swing.border.BevelBorder.RAISED));
		jLabel2.addMouseListener(new MouseListener() {

			public void mouseReleased(MouseEvent e) {
				dispose();
				new SelectBooks(nickname).setVisible(true);
			}

			public void mousePressed(MouseEvent e) {

			}

			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
			}

			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
			}

			public void mouseClicked(MouseEvent e) {

			}
		});

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel4.setForeground(new java.awt.Color(102, 102, 102));
		jLabel4.setText("\u4f5c\u8005:");

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel5.setForeground(new java.awt.Color(102, 102, 102));
		jLabel5.setText("\u51fa\u7248\u793e:");

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel6.setForeground(new java.awt.Color(102, 102, 102));
		jLabel6.setText("\u539f\u4f5c\u540d:");

		jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel7.setForeground(new java.awt.Color(102, 102, 102));
		jLabel7.setText("\u8bd1\u8005:");

		jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel8.setForeground(new java.awt.Color(102, 102, 102));
		jLabel8.setText("\u51fa\u7248\u5e74:");

		jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel9.setForeground(new java.awt.Color(102, 102, 102));
		jLabel9.setText("\u9875\u6570:");

		jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel10.setForeground(new java.awt.Color(102, 102, 102));
		jLabel10.setText("\u5b9a\u4ef7:");

		jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel11.setForeground(new java.awt.Color(102, 102, 102));
		jLabel11.setText("\u4e1b\u4e66:");

		jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel12.setForeground(new java.awt.Color(102, 102, 102));
		jLabel12.setText("ISBN:");

		jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel13.setText("[\u7f8e]\u94a0\u535a\u79d1\u592b");

		jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel14.setText("\u4e0a\u6d77\u8bd1\u6587\u51fa\u7248\u793e");

		jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel15.setText("Strong Opinions");

		jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel16.setText("\u5510\u5efa\u6e05");

		jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel17.setText("2018-9-1");

		jLabel18.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel18.setText("334");

		jLabel19.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel19.setText("\u7eb3\u535a\u79d1\u592b\u4f5c\u54c1\u7cfb\u5217");

		jLabel20.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel20.setText("58");

		jLabel21.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 21));
		jLabel21.setText("9787532776320");

		jButton1.setText("\u6536\u85cf");
		jButton1.setFocusable(false);

		jButton2.setText("\u4fee\u6539");

		jButton2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				String status = null;
				String sql = "select * from test where nickname = '"+nickname+"'";
				try {
					ResultSet rs = DB_Connect.getStatement().executeQuery(sql);
					while(rs.next()){
						status = rs.getString(5);
					}
				} catch (SQLException e1) {
					e1.printStackTrace();
				}
				if(status.equals("1")){
					if(i==0){
						jButton2.setText("保存");
						jTextArea1.setEditable(true);
						i = 1;
					}
					else if(i == 1){
						JOptionPane.showMessageDialog(null, "保存成功");
						jButton2.setText("修改");
						jTextArea1.setEditable(false);
						i = 0;
					}
					
				}
				else{
					JOptionPane.showMessageDialog(null, "非作者操作，禁止进行");
					return;
				}
			}
		});
		jButton3.setText("\u5206\u4eab");
		jButton3.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (nickname==null) {
					JOptionPane.showMessageDialog(null, "请先进行登陆");
					new NovelLogin().setVisible(true);
					dispose();
					return;
				}
				new share_sure(nickname, bookname).setVisible(true);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																197,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel1))
										.addGap(28, 28, 28)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel11)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel19))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel12)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel21))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel5)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel14))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel13))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel8)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel17))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel10)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel20))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel9)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel18))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel7)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel16))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel15))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton1)
																		.addGap(
																				29,
																				29,
																				29)
																		.addComponent(
																				jButton3)))
										.addContainerGap(45, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				33,
																				33,
																				33)
																		.addComponent(
																				jLabel1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				20,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel2Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton1)
																						.addComponent(
																								jButton3))
																		.addGap(
																				29,
																				29,
																				29)))
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jLabel13))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel5)
																						.addComponent(
																								jLabel14))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								jLabel15))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								jLabel16))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel8)
																						.addComponent(
																								jLabel17))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel9)
																						.addComponent(
																								jLabel18))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel10)
																						.addComponent(
																								jLabel20))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel11)
																						.addComponent(
																								jLabel19))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel12)
																						.addComponent(
																								jLabel21)))
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																315,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(69, 69, 69)));

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));

		jLabel22.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 28));
		jLabel22.setForeground(new java.awt.Color(0, 102, 102));
		jLabel22.setText("\u5185\u5bb9\u7b80\u4ecb . . . . . .");

		jTextArea1.setFont(new java.awt.Font("黑体", 0, 24));
		Color c = new Color(210, 180, 162);
		jTextArea1.setForeground(c);
		jTextArea1.setRows(5);
		jTextArea1.setColumns(20);
		jTextArea1.setLineWrap(true);
		jScrollPane1.setViewportView(jTextArea1);
		jTextArea1.setEditable(false);

		jButton4.setText("\u8bc4\u8bba\u7559\u8a00");
		jButton4.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (nickname==null) {
					JOptionPane.showMessageDialog(null, "请先进行登陆");
					new NovelLogin().setVisible(true);
					dispose();
					return;
				}
				new comment(bookname, nickname).setVisible(true);
			}
		});

		jButton5.setText("\u5173\u6ce8\u4f5c\u8005");
		jButton5.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (nickname==null) {
					JOptionPane.showMessageDialog(null, "请先进行登陆");
					new NovelLogin().setVisible(true);
					dispose();
					return;
				}
				String author = jLabel13.getText();
				try {
					Client c = new Client();
					User u = c.mark_author(nickname, author);
				} catch (Exception e1) {
					e1.printStackTrace();
				}
				
			}
		});
		
		jButton6.setText("\u8d2d\u4e70\u6b64\u4e66");
		jButton6.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (nickname==null) {
					JOptionPane.showMessageDialog(null, "请先进行登陆");
					new NovelLogin().setVisible(true);
					dispose();
					return;
				}
				new buy(nickname, bookname).setVisible(true);
			}
		});

		jButton7.setText("\u514d\u8d39\u8bd5\u8bfb");
		jButton7.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				new BookContent(id,nickname).setVisible(true);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(39, 39, 39)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel22)
																		.addGap(
																				49,
																				49,
																				49)
																		.addComponent(
																				jButton2))
														.addGroup(
																jPanel3Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addGroup(
																				jPanel3Layout
																						.createSequentialGroup()
																						.addComponent(
																								jButton7)
																						.addGap(
																								34,
																								34,
																								34)
																						.addComponent(
																								jButton6)
																						.addGap(
																								32,
																								32,
																								32)
																						.addComponent(
																								jButton5)
																						.addGap(
																								33,
																								33,
																								33)
																						.addComponent(
																								jButton4))
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				539,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(41, Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(40, 40, 40)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel22)
														.addComponent(jButton2))
										.addGap(28, 28, 28)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												320,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												63, Short.MAX_VALUE)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton5)
														.addComponent(jButton4)
														.addComponent(jButton6)
														.addComponent(jButton7))
										.addContainerGap()));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(
												jPanel2,
												670,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel2, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
				Short.MAX_VALUE).addComponent(jPanel3,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				400, Short.MAX_VALUE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				1315,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		try {
			org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
		} catch (Exception e) {
			// TODO exception
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new BookIntroduce(nickname, null, id).setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	public javax.swing.JLabel jLabel1;
	public javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	public javax.swing.JLabel jLabel13;
	public javax.swing.JLabel jLabel14;
	public javax.swing.JLabel jLabel15;
	public javax.swing.JLabel jLabel16;
	public javax.swing.JLabel jLabel17;
	public javax.swing.JLabel jLabel18;
	public javax.swing.JLabel jLabel19;
	public javax.swing.JLabel jLabel2;
	public javax.swing.JLabel jLabel20;
	public javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	public javax.swing.JScrollPane jScrollPane1;
	public javax.swing.JTextArea jTextArea1;
	// End of variables declaration//GEN-END:variables

}