/*
 * BookContent.java
 *
 * Created on __DATE__, __TIME__
 */

package novel;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

/**
 * 
 * @author __USER__
 */
public class BookContent extends javax.swing.JFrame {

	static int id = 0;
	static String name = null;
	String status = null;

	/** Creates new form BookContent */
	public BookContent(int id, String name) {
		this.id = id;
		this.name = name;
		initComponents(id, name);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents(int id, String name) {

		this.setTitle("乐阅悦");
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(229, 228, 219));

		jTextArea1.setBackground(new java.awt.Color(246, 244, 236));
		jTextArea1.setColumns(20);
		jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 18));
		jTextArea1.setRows(5);

		String sql = "select * from book_comment where id=" + id + "";
		String bookname = "";
		String comment = "";
		try {
			ResultSet rs = DB_NovelLists.getStatement().executeQuery(sql);
			while (rs.next()) {
				bookname = rs.getString(2);
				comment = rs.getString(3);
			}
		} catch (SQLException e1) {
			e1.printStackTrace();
		}
		jTextArea1.setText(bookname + '\n' + comment);

		String query = "select * from test where nickname='" + name + "'";
		try {
			ResultSet rs = DB_Connect.getStatement().executeQuery(query);
			while (rs.next()) {
				status = rs.getString(5);
			}
		} catch (SQLException e1) {
			e1.printStackTrace();
		}
		jTextArea1.setEditable(false);
		jScrollPane1.setViewportView(jTextArea1);
		jTextArea1.setLineWrap(true);
		jTextArea1.addMouseListener(new mouseC());

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448,
				Short.MAX_VALUE));

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 48));
		jLabel1.setForeground(new java.awt.Color(0, 0, 0));
		jLabel1.setText("|>");
		jLabel1.addMouseListener(new MouseListener() {
			Color c = new Color(0, 0, 0);

			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				jLabel1.setForeground(c);
			}

			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				jLabel1.setForeground(Color.white);
			}

			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub

			}
		});

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 48));
		jLabel2.setForeground(new java.awt.Color(0, 0, 0));
		jLabel2.setText("<|");
		jLabel2.addMouseListener(new MouseListener() {
			Color c = new Color(0, 0, 0);

			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				jLabel2.setForeground(c);
			}

			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				jLabel2.setForeground(Color.white);
			}

			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub

			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel1Layout.createSequentialGroup().addContainerGap(
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 49,
								javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
								33, 33, 33).addComponent(jPanel2,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
								18, 18, 18).addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 49,
								javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
								55, 55, 55)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				238,
																				238,
																				238)
																		.addComponent(
																				jLabel2))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				237,
																				237,
																				237)
																		.addComponent(
																				jLabel1))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				48,
																				48,
																				48)
																		.addComponent(
																				jPanel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(51, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 848,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new BookContent(id, name).setVisible(true);
			}
		});
	}

	// 鼠标监听重写
	class mouseC extends MouseAdapter {
		int i = 0;

		public void mouseClicked(MouseEvent arg0) {
			if (arg0.getButton() == MouseEvent.BUTTON1) {
				// 左键点击
				if (status.equals("1")) {
					i++;
					if (i < 2) {
						jTextArea1.setEditable(true);
						JOptionPane.showMessageDialog(null, "左键编辑，右键保存");
					}
				} else {
					if(i<2){
						JOptionPane.showMessageDialog(null, "非作者不能更改书籍内容");
						i++;
					}
				}
			} else if (arg0.getButton() == MouseEvent.BUTTON3) {
				// 右键点击
				if (status.equals("1")) {
					int selected2 = JOptionPane.showConfirmDialog(null,
							"确认保存更改吗", "请确认", JOptionPane.YES_NO_OPTION);
					if (selected2 == 0) {
						JOptionPane.showMessageDialog(null, "保存成功！");
						jTextArea1.setEditable(false);
					}
				}
			}
		}
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	// End of variables declaration//GEN-END:variables

}