/*
 * List.java
 *
 * Created on __DATE__, __TIME__
 */

package novel;

import java.awt.Image;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;

import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author  __USER__
 */
public class List extends javax.swing.JFrame {

	/** Creates new form List */
	public List() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		this.setTitle("小说排行榜");
		jPanel1 = new javax.swing.JPanel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jPanel4 = new javax.swing.JPanel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTable3 = new javax.swing.JTable();
		jPanel5 = new javax.swing.JPanel();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTable4 = new javax.swing.JTable();
		jPanel6 = new javax.swing.JPanel();
		jScrollPane5 = new javax.swing.JScrollPane();
		jTable5 = new javax.swing.JTable();
		jPanel7 = new javax.swing.JPanel();
		jScrollPane6 = new javax.swing.JScrollPane();
		jTable6 = new javax.swing.JTable();
		jPanel8 = new javax.swing.JPanel();
		jScrollPane7 = new javax.swing.JScrollPane();
		jTable7 = new javax.swing.JTable();
		jPanel9 = new javax.swing.JPanel();
		jScrollPane8 = new javax.swing.JScrollPane();
		jTable8 = new javax.swing.JTable();
		jPanel10 = new javax.swing.JPanel();
		jScrollPane9 = new javax.swing.JScrollPane();
		jTable9 = new javax.swing.JTable();
		jPanel11 = new javax.swing.JPanel();
		jScrollPane10 = new javax.swing.JScrollPane();
		jTable10 = new javax.swing.JTable();
		jPanel12 = new javax.swing.JPanel();
		jScrollPane11 = new javax.swing.JScrollPane();
		jTable11 = new javax.swing.JTable();
		jPanel13 = new javax.swing.JPanel();
		jScrollPane12 = new javax.swing.JScrollPane();
		jTable12 = new javax.swing.JTable();
		jPanel14 = new javax.swing.JPanel();
		jScrollPane13 = new javax.swing.JScrollPane();
		jTable13 = new javax.swing.JTable();
		jPanel15 = new javax.swing.JPanel();
		jScrollPane14 = new javax.swing.JScrollPane();
		jTable14 = new javax.swing.JTable();
		jPanel16 = new javax.swing.JPanel();
		jScrollPane15 = new javax.swing.JScrollPane();
		jTable15 = new javax.swing.JTable();
		jPanel17 = new javax.swing.JPanel();
		jScrollPane16 = new javax.swing.JScrollPane();
		jTable16 = new javax.swing.JTable();
		jPanel18 = new javax.swing.JPanel();
		jScrollPane17 = new javax.swing.JScrollPane();
		jTable17 = new javax.swing.JTable();
		jPanel19 = new javax.swing.JPanel();
		jScrollPane18 = new javax.swing.JScrollPane();
		jTable18 = new javax.swing.JTable();
		jPanel20 = new javax.swing.JPanel();
		jScrollPane19 = new javax.swing.JScrollPane();
		jTable19 = new javax.swing.JTable();
		jPanel21 = new javax.swing.JPanel();
		jScrollPane20 = new javax.swing.JScrollPane();
		jTable20 = new javax.swing.JTable();
		jPanel22 = new javax.swing.JPanel();
		jScrollPane21 = new javax.swing.JScrollPane();
		jTable21 = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		get_table(jTable1, "top_click",jScrollPane1);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel2Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("点击排行榜", jPanel2);

		get_table(jTable2, "top_jinbi",jScrollPane2);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addComponent(jScrollPane2,
				javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel3Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane2,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("金笔排行榜", jPanel3);

		get_table(jTable3, "top_huopiao",jScrollPane3);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addComponent(
				jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
				Short.MAX_VALUE));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel4Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane3,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("火票排行榜", jPanel4);

		get_table(jTable4, "top_dashang",jScrollPane4);

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addComponent(jScrollPane4,
				javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel5Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane4,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("打赏排行榜", jPanel5);

		get_table(jTable5, "top_new",jScrollPane5);

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addComponent(jScrollPane5,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
						Short.MAX_VALUE));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel6Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane5,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("新书风云榜", jPanel6);

		get_table(jTable6, "top_qingfen",jScrollPane6);

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
				jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(
				0, 1051, Short.MAX_VALUE).addComponent(jScrollPane6,
				javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE));
		jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel7Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane6,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("勤奋更新榜", jPanel7);

		get_table(jTable7, "top_city",jScrollPane7);

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(
				jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(
				0, 1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addComponent(jScrollPane7,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
						Short.MAX_VALUE));
		jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel8Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane7,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("都市小说榜", jPanel8);

		get_table(jTable8, "top_xuanhuan",jScrollPane8);

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(
				jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(
				0, 1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addComponent(jScrollPane8,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
						Short.MAX_VALUE));
		jPanel9Layout.setVerticalGroup(jPanel9Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel9Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane8,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("玄幻小说榜", jPanel9);

		get_table(jTable9, "top_collect",jScrollPane9);

		javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(
				jPanel10);
		jPanel10.setLayout(jPanel10Layout);
		jPanel10Layout.setHorizontalGroup(jPanel10Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(
				0, 1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addComponent(jScrollPane9,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
						Short.MAX_VALUE));
		jPanel10Layout.setVerticalGroup(jPanel10Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel10Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane9,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("有效收藏排行榜", jPanel10);

		get_table(jTable10, "top_qihuan",jScrollPane10);

		javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(
				jPanel11);
		jPanel11.setLayout(jPanel11Layout);
		jPanel11Layout.setHorizontalGroup(jPanel11Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(
				0, 1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addComponent(jScrollPane10,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
						Short.MAX_VALUE));
		jPanel11Layout.setVerticalGroup(jPanel11Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel11Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane10,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("奇幻小说榜", jPanel11);

		get_table(jTable11, "top_wuxia",jScrollPane11);

		javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(
				jPanel12);
		jPanel12.setLayout(jPanel12Layout);
		jPanel12Layout.setHorizontalGroup(jPanel12Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(
				0, 1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addComponent(jScrollPane11,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
						Short.MAX_VALUE));
		jPanel12Layout.setVerticalGroup(jPanel12Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel12Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane11,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("武侠小说榜", jPanel12);

		get_table(jTable12, "top_xianxia",jScrollPane12);

		javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(
				jPanel13);
		jPanel13.setLayout(jPanel13Layout);
		jPanel13Layout.setHorizontalGroup(jPanel13Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(
				0, 1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addComponent(jScrollPane12,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
						Short.MAX_VALUE));
		jPanel13Layout.setVerticalGroup(jPanel13Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel13Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane12,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("仙侠小说榜", jPanel13);

		get_table(jTable13, "top_love",jScrollPane13);

		javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(
				jPanel14);
		jPanel14.setLayout(jPanel14Layout);
		jPanel14Layout.setHorizontalGroup(jPanel14Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(
				0, 1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addComponent(jScrollPane13,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
						Short.MAX_VALUE));
		jPanel14Layout.setVerticalGroup(jPanel14Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel14Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane13,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("言情小说榜", jPanel14);

		get_table(jTable14, "top_history",jScrollPane14);

		javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(
				jPanel15);
		jPanel15.setLayout(jPanel15Layout);
		jPanel15Layout.setHorizontalGroup(jPanel15Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(
				0, 1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addComponent(jScrollPane14,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
						Short.MAX_VALUE));
		jPanel15Layout.setVerticalGroup(jPanel15Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel15Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane14,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("历史小说榜", jPanel15);

		get_table(jTable15, "top_junshi",jScrollPane15);

		javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(
				jPanel16);
		jPanel16.setLayout(jPanel16Layout);
		jPanel16Layout.setHorizontalGroup(jPanel16Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(
				0, 1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addComponent(jScrollPane15,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
						Short.MAX_VALUE));
		jPanel16Layout.setVerticalGroup(jPanel16Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel16Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane15,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("军事小说榜", jPanel16);

		get_table(jTable16, "top_game",jScrollPane16);

		javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(
				jPanel17);
		jPanel17.setLayout(jPanel17Layout);
		jPanel17Layout.setHorizontalGroup(jPanel17Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(
				0, 1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addComponent(jScrollPane16,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
						Short.MAX_VALUE));
		jPanel17Layout.setVerticalGroup(jPanel17Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel17Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane16,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("游戏小说榜", jPanel17);

		get_table(jTable17, "top_kehuan",jScrollPane17);

		javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(
				jPanel18);
		jPanel18.setLayout(jPanel18Layout);
		jPanel18Layout.setHorizontalGroup(jPanel18Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(
				0, 1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addComponent(jScrollPane17,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
						Short.MAX_VALUE));
		jPanel18Layout.setVerticalGroup(jPanel18Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel18Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane17,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("科幻小说榜", jPanel18);

		get_table(jTable18, "top_kongbu",jScrollPane18);

		javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(
				jPanel19);
		jPanel19.setLayout(jPanel19Layout);
		jPanel19Layout.setHorizontalGroup(jPanel19Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(
				0, 1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addComponent(jScrollPane18,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
						Short.MAX_VALUE));
		jPanel19Layout.setVerticalGroup(jPanel19Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel19Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane18,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("恐怖小说榜", jPanel19);

		get_table(jTable19, "top_jingji",jScrollPane19);

		javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(
				jPanel20);
		jPanel20.setLayout(jPanel20Layout);
		jPanel20Layout.setHorizontalGroup(jPanel20Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(
				0, 1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addComponent(jScrollPane19,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
						Short.MAX_VALUE));
		jPanel20Layout.setVerticalGroup(jPanel20Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel20Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane19,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("竞技小说榜", jPanel20);

		get_table(jTable20, "top_download",jScrollPane20);

		javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(
				jPanel21);
		jPanel21.setLayout(jPanel21Layout);
		jPanel21Layout.setHorizontalGroup(jPanel21Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(
				0, 1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addComponent(jScrollPane20,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
						Short.MAX_VALUE));
		jPanel21Layout.setVerticalGroup(jPanel21Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel21Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane20,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("下载排行榜", jPanel21);

		get_table(jTable21, "top_bingpiao",jScrollPane21);

		javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(
				jPanel22);
		jPanel22.setLayout(jPanel22Layout);
		jPanel22Layout.setHorizontalGroup(jPanel22Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1051,
				Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(0,
				1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE).addGap(
				0, 1051, Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addGap(0, 1051, Short.MAX_VALUE)
				.addGap(0, 1051, Short.MAX_VALUE).addGap(0, 1051,
						Short.MAX_VALUE).addComponent(jScrollPane21,
						javax.swing.GroupLayout.DEFAULT_SIZE, 1051,
						Short.MAX_VALUE));
		jPanel22Layout.setVerticalGroup(jPanel22Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGap(0, 544,
				Short.MAX_VALUE).addGap(0, 544, Short.MAX_VALUE).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel22Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane21,
								javax.swing.GroupLayout.DEFAULT_SIZE, 528,
								Short.MAX_VALUE)));

		jTabbedPane1.addTab("冰票排行榜", jPanel22);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36));
		jLabel1.setText("\u5c0f\u8bf4\u6392\u884c\u699c\u5927\u5168");

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24));
		jLabel2.setText("2018\u5e74\u6392\u884c\u699c");

		Image img0 = new ImageIcon("src\\img\\bang.gif").getImage()
		.getScaledInstance( 42,47, Image.SCALE_SMOOTH);
		jLabel3.setIcon(new ImageIcon(img0));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jTabbedPane1,
								javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE, 1056,
								Short.MAX_VALUE)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												535, Short.MAX_VALUE)
										.addComponent(jLabel3).addGap(18, 18,
												18).addComponent(jLabel2)
										.addGap(28, 28, 28)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addGroup(
																				jPanel1Layout
																						.createSequentialGroup()
																						.addGap(
																								31,
																								31,
																								31)
																						.addComponent(
																								jLabel1)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																								33,
																								Short.MAX_VALUE))
																		.addGroup(
																				jPanel1Layout
																						.createSequentialGroup()
																						.addGap(
																								70,
																								70,
																								70)
																						.addComponent(
																								jLabel2)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jLabel3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				50,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
										.addComponent(
												jTabbedPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												578,
												javax.swing.GroupLayout.PREFERRED_SIZE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		try {
			org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new List().setVisible(true);
			}
		});
	}

	public void get_table(JTable table,String db_table,JScrollPane jsp){
		ResultSetMetaData rsd = null;
		Vector col = new Vector(); // col存入字段名
		Vector dat = new Vector(); // 存入数据内容

		ResultSet rs;
		try {
			rs = DB_NovelLists.getStatement().executeQuery(
					"select * from "+db_table+"");
			rsd = rs.getMetaData(); // 获得表结构
			for (int i = 1; i <= rsd.getColumnCount(); i++) { // getColumnCount
				// 获得列数
				col.add(rsd.getColumnName(i)); // 获得每一列的属性名
			}
			// 按行依次读取每个数据
			while (rs.next()) {
				Vector v = new Vector();
				for (int i = 1; i <= rsd.getColumnCount(); i++) {
					String rs_get = rs.getString(i);
					v.addElement(rs_get);
				}
				dat.addElement(v);
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		// System.out.println("数据库加载成功!");

		table = new JTable(dat, col);
		jsp.setViewportView(table);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel12;
	private javax.swing.JPanel jPanel13;
	private javax.swing.JPanel jPanel14;
	private javax.swing.JPanel jPanel15;
	private javax.swing.JPanel jPanel16;
	private javax.swing.JPanel jPanel17;
	private javax.swing.JPanel jPanel18;
	private javax.swing.JPanel jPanel19;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel20;
	private javax.swing.JPanel jPanel21;
	private javax.swing.JPanel jPanel22;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane10;
	private javax.swing.JScrollPane jScrollPane11;
	private javax.swing.JScrollPane jScrollPane12;
	private javax.swing.JScrollPane jScrollPane13;
	private javax.swing.JScrollPane jScrollPane14;
	private javax.swing.JScrollPane jScrollPane15;
	private javax.swing.JScrollPane jScrollPane16;
	private javax.swing.JScrollPane jScrollPane17;
	private javax.swing.JScrollPane jScrollPane18;
	private javax.swing.JScrollPane jScrollPane19;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane20;
	private javax.swing.JScrollPane jScrollPane21;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JScrollPane jScrollPane6;
	private javax.swing.JScrollPane jScrollPane7;
	private javax.swing.JScrollPane jScrollPane8;
	private javax.swing.JScrollPane jScrollPane9;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable jTable10;
	private javax.swing.JTable jTable11;
	private javax.swing.JTable jTable12;
	private javax.swing.JTable jTable13;
	private javax.swing.JTable jTable14;
	private javax.swing.JTable jTable15;
	private javax.swing.JTable jTable16;
	private javax.swing.JTable jTable17;
	private javax.swing.JTable jTable18;
	private javax.swing.JTable jTable19;
	private javax.swing.JTable jTable2;
	private javax.swing.JTable jTable20;
	private javax.swing.JTable jTable21;
	private javax.swing.JTable jTable3;
	private javax.swing.JTable jTable4;
	private javax.swing.JTable jTable5;
	private javax.swing.JTable jTable6;
	private javax.swing.JTable jTable7;
	private javax.swing.JTable jTable8;
	private javax.swing.JTable jTable9;
	// End of variables declaration//GEN-END:variables

}