/*
 * Manger.java
 *
 * Created on __DATE__, __TIME__
 */

package novel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 * 
 * @author __USER__
 */
public class Manger extends javax.swing.JFrame {

	static String nickname = null;

	/** Creates new form Manger */
	public Manger(String nickname) {
		this.nickname = nickname;
		initComponents(nickname);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents(final String nickname) {

		this.setTitle("管理中心");
		jPanel1 = new javax.swing.JPanel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jLabel1 = new javax.swing.JLabel();
		jButton4 = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jButton5 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		final get_table gt = new get_table();
		final Thread t = new Thread(gt);
		t.start();

		jButton1.setText("\u5220\u9664\u7528\u6237");
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					// 直接获取昵称
					String user_nickname = (String) jTable1.getModel()
							.getValueAt(jTable1.getSelectedRow(), 3);
					String status = (String) jTable1.getModel().getValueAt(
							jTable1.getSelectedRow(), 4);
					if (status.equals("管理员")) {
						JOptionPane.showMessageDialog(null, "无法删除管理员："
								+ user_nickname);
						return;
					}
					int selected = JOptionPane.showConfirmDialog(null, "确认删除"
							+ status + "：" + user_nickname + "?", "请确认",
							JOptionPane.YES_NO_OPTION);
					// System.out.println(showConfirmDialog);
					if (selected == 0) {
						String sql = "delete from test where nickname = '"
								+ user_nickname + "'";
						try {
							DB_Connect.getStatement().executeUpdate(sql);
							JOptionPane.showMessageDialog(null, status + "："
									+ user_nickname + "，已被移除");
						} catch (Exception e2) {
							JOptionPane.showMessageDialog(null, "删除失败");
							// e2.printStackTrace();
						}

					} else {

					}
				} catch (Exception e1) {
					JOptionPane.showMessageDialog(null, "您没用选中用户呢");
				}

			}
		});

		jButton2.setText("\u66f4\u6539\u4fe1\u606f");
		jButton2.addActionListener(new ActionListener() {
			@SuppressWarnings("deprecation")
			public void actionPerformed(ActionEvent e) {
				t.stop();
				try {
					String id = (String) jTable1.getModel().getValueAt(
							jTable1.getSelectedRow(), 0);
					String account = (String) jTable1.getModel().getValueAt(
							jTable1.getSelectedRow(), 1);
					String password = (String) jTable1.getModel().getValueAt(
							jTable1.getSelectedRow(), 2);
					String user_nickname = (String) jTable1.getModel()
							.getValueAt(jTable1.getSelectedRow(), 3);
					String status = (String) jTable1.getModel().getValueAt(
							jTable1.getSelectedRow(), 4);

					if (status.equals("管理员")) {
						JOptionPane.showMessageDialog(null, "禁止更改管理员信息");
						return;
					}
					int selected = JOptionPane.showConfirmDialog(null, "确认更改："
							+ user_nickname + "的信息吗？", "请确认",
							JOptionPane.YES_NO_OPTION);
					if (selected == 0) {
						String sql = "update test set account='" + account
								+ "',password='" + password + "',nickname='"
								+ user_nickname + "' where id=" + id + "";
						// System.out.println(sql);
						try {
							DB_Connect.getStatement().executeUpdate(sql);
							JOptionPane.showMessageDialog(null, user_nickname
									+ "信息更改成功(身份无法更改)");
							Thread t = new Thread(gt);
							t.start();
						} catch (Exception e3) {
							JOptionPane.showMessageDialog(null, "更改失败");
							e3.printStackTrace();
							return;
						}
					} else {

					}
				} catch (Exception e1) {
					JOptionPane.showMessageDialog(null, "您还没有选中用户噢");
				}

			}
		});

		jButton3.setText("\u9000\u51fa\u7cfb\u7edf");
		jButton3.addActionListener(new ActionListener() {
			@SuppressWarnings("deprecation")
			public void actionPerformed(ActionEvent e) {
				try {
					t.stop();
				} catch (Exception e1) {
					e1.printStackTrace();
				}
				dispose();
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(46, 46, 46)
										.addComponent(jButton1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												112, Short.MAX_VALUE)
										.addComponent(jButton2).addGap(105,
												105, 105)
										.addComponent(jButton3).addGap(49, 49,
												49)).addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 591,
								Short.MAX_VALUE));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												354, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jButton3)
														.addComponent(jButton2))
										.addContainerGap()));

		jTabbedPane1.addTab("\u7528\u6237\u7ba1\u7406", jPanel2);

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane2.setViewportView(jTextArea1);

		jLabel1.setFont(new java.awt.Font("宋体", 0, 24));
		jLabel1.setText("\u7f16\u8f91\u516c\u544a");

		jButton4.setText("\u786e\u5b9a\u53d1\u5e03");
		jButton4.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				Date date = new Date();
				SimpleDateFormat dateFormat = new SimpleDateFormat(
						"yyyy-MM-dd HH:mm:ss");
				String time = String.valueOf(dateFormat.format(date));
				String content = jTextArea1.getText();
				String sql = "insert into notice(`nickname`,`content`,`time`) values ('"
						+ nickname + "','" + content + "','" + time + "')";
				int selected = JOptionPane.showConfirmDialog(null, "确认发布公告吗？",
						"请确认", JOptionPane.YES_NO_OPTION);
				if (selected == 0) {
					try {
						DB_Connect.getStatement().executeUpdate(sql);
						JOptionPane.showMessageDialog(null, "发布成功");
						jButton4.setText("重新发布");
					} catch (SQLException e1) {
						e1.printStackTrace();
					}
				}
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(74, 74, 74)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jButton4)
														.addGroup(
																jPanel3Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(
																				jScrollPane2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				439,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel1)))
										.addContainerGap(78, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel3Layout.createSequentialGroup().addContainerGap(33,
						Short.MAX_VALUE).addComponent(jLabel1).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 264,
								javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
								26, 26, 26).addComponent(jButton4).addGap(25,
								25, 25)));

		jTabbedPane1.addTab("\u53d1\u5e03\u516c\u544a", jPanel3);

		jLabel2.setFont(new java.awt.Font("宋体", 0, 24));
		jLabel2.setText("\u65e5\u63a8\u53d1\u5e03");

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jScrollPane3.setViewportView(jTextArea2);

		jButton5.setText("\u53d1\u5e03\u65e5\u63a8");
		jButton5.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				Date date = new Date();
				SimpleDateFormat dateFormat = new SimpleDateFormat(
						"yyyy-MM-dd HH:mm:ss");
				String time = String.valueOf(dateFormat.format(date));
				String bookname = jTextArea2.getText();
				String sql = "insert into recommend(`nickname`,`content`,`time`) values ('"
						+ nickname + "','" + bookname + "','" + time + "')";
				int selected = JOptionPane.showConfirmDialog(null, "确认发布日推吗？",
						"请确认", JOptionPane.YES_NO_OPTION);
				if (selected == 0) {
					try {
						DB_Connect.getStatement().executeUpdate(sql);
						JOptionPane.showMessageDialog(null, "发布成功");
						jButton5.setText("重新发布");
					} catch (SQLException e1) {
						e1.printStackTrace();
					}
				}
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(66, 66, 66)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jButton5)
														.addGroup(
																jPanel4Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(
																				jScrollPane3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				445,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel2)))
										.addContainerGap(80, Short.MAX_VALUE)));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(40, 40, 40)
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												238,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												35, Short.MAX_VALUE)
										.addComponent(jButton5).addGap(35, 35,
												35)));

		jTabbedPane1.addTab("\u53d1\u5e03\u65e5\u63a8", jPanel4);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596,
				Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Manger(nickname).setVisible(true);
			}
		});
	}

	class get_table implements Runnable {
		@SuppressWarnings("unchecked")
		public void run() {
			while (true) {
				ResultSetMetaData rsd = null;
				Vector col = new Vector(); // col存入字段名
				Vector dat = new Vector(); // 存入数据内容

				ResultSet rs;
				try {
					rs = DB_Connect.getStatement().executeQuery(
							"select * from test");
					rsd = rs.getMetaData(); // 获得表结构
					for (int i = 1; i <= rsd.getColumnCount() - 5; i++) { // getColumnCount
						// 获得列数
						col.add(rsd.getColumnName(i)); // 获得每一列的属性名
					}
					// 按行依次读取每个数据
					while (rs.next()) {
						Vector v = new Vector();
						for (int i = 1; i <= rsd.getColumnCount() - 5; i++) {
							String rs_get = rs.getString(i);
							if (rs.getString(i).equals("0")&&i==5) {
								rs_get = "读者";
							} else if (rs.getString(i).equals("1")&&i==5) {
								rs_get = "作者";
							} else if (rs.getString(i).equals("2")&&i==5) {
								rs_get = "管理员";
							} else {
								rs_get = rs.getString(i);
							}
							v.addElement(rs_get);
						}
						dat.addElement(v);
					}
				} catch (SQLException e) {
					e.printStackTrace();
				}
				// System.out.println("数据库加载成功!");

				jTable1 = new JTable(dat, col);
				jScrollPane1.setViewportView(jTable1);
				try {
					Thread.sleep(4500);
				} catch (InterruptedException e) {
					e.printStackTrace();
					return;
				}
			}

		}
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	// End of variables declaration//GEN-END:variables

}