/*
 * NovelRegister.java
 *
 * Created on __DATE__, __TIME__
 */

package novel;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.regex.Pattern;

import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

import check_code.CheckCode;

import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;

/**
 *
 * @author  __USER__
 */
@SuppressWarnings("serial")
public class NovelRegister extends javax.swing.JFrame implements ActionListener {

	/** Creates new form NovelRegister */
	public NovelRegister() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents(){
		this.setTitle("注册界面");
		this.setResizable(false);
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jPasswordField1 = new javax.swing.JPasswordField();
		jLabel8 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jTextField2 = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/icon1.jpg"))); // NOI18N

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/icon3.jpg"))); // NOI18N

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel3.setText("\u90ae\u7bb1");

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel4.setText("\u5bc6\u7801");

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel5.setText("\u6635\u79f0");

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel6.setText("\u9a8c\u8bc1\u7801");

		jTextField1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jTextField1.setText("");
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jTextField3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jTextField3.setText("1 to 10 digits");
		jTextField3.setForeground(Color.gray);
		jTextField3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField3ActionPerformed(evt);
			}
		});
		jTextField3.addFocusListener(new FocusListener() {
			
			@Override
			public void focusLost(FocusEvent e) {
				// TODO Auto-generated method stub
				if(jTextField3.getText().equals("")){
					jTextField3.setForeground(Color.gray);
					jTextField3.setText("1 to 10 digits");
				}
			}
			@Override
			public void focusGained(FocusEvent e) {
				// TODO Auto-generated method stub
				if(jTextField3.getText().equals("1 to 10 digits")){
					jTextField3.setText("");
					jTextField3.setForeground(Color.black);
				}
			}
		});
		jTextField3.addKeyListener(new KeyListener() {
			
			@Override
			public void keyTyped(KeyEvent e) {
				
			}
			
			@Override
			public void keyReleased(KeyEvent e) {
				jTextField3.setEditable(true);
			}
			
			@Override
			public void keyPressed(KeyEvent e) {
				if(e.getKeyChar()==KeyEvent.VK_SPACE){
					jTextField3.setEditable(false);
				}
			}
		});

		jTextField4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jTextField4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField4ActionPerformed(evt);
			}
		});

		jLabel7.setOpaque(true);
		jLabel7.setBackground(new java.awt.Color(240, 240, 240));
		jLabel7.setForeground(rand_color.RandColor.randomColor());
		jLabel7.setBorder(BorderFactory.createLineBorder(Color.black));
		jLabel7.setFont(new java.awt.Font("宋体", 0, 17));
		jLabel7.setText(CheckCode.getRandomCode(4));
		System.out.println(jLabel7.getText().replaceAll(" ",""));
		jLabel7.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				jLabel7.setForeground(rand_color.RandColor.randomColor());
				jLabel7.setText(CheckCode.getRandomCode(4));
				System.out.println(jLabel7.getText().replaceAll(" ",""));
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
		});

		jButton1.setBackground(new java.awt.Color(63, 161, 86));
		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 17));
		jButton1.setForeground(new java.awt.Color(0, 0, 0));
		jButton1.setText("\u6ce8\u518c");
		jButton1.setFocusable(false);
		jButton1.addMouseListener(new MouseListener() {
			Color a = new Color(63,161,86);
			Color b = new Color(79,202,108);
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				jButton1.setBackground(b);
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				jButton1.setBackground(a);
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				setCursor(Cursor.getDefaultCursor());
				jButton1.setBackground(a);
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
				jButton1.setOpaque(true);
				jButton1.setBackground(b);
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
			}
		});
		//��ť�¼�����
		jButton1.addActionListener(this);

		jPasswordField1.setFont(new java.awt.Font("黑体", 0, 16));
		jPasswordField1.setEchoChar((char) 0);
		jPasswordField1.setText("At least 6 digits");
		jPasswordField1.setForeground(Color.gray);
		jPasswordField1.addFocusListener(new FocusListener() {
			
			@Override
			public void focusLost(FocusEvent e) {
				// TODO Auto-generated method stub
				if(String.valueOf(jPasswordField1.getPassword()).equals("")){
					jPasswordField1.setForeground(Color.gray);
					jPasswordField1.setEchoChar((char) 0);
					jPasswordField1.setText("At least 6 digits");
				}
			}
			@Override
			public void focusGained(FocusEvent e) {
				// TODO Auto-generated method stub
				if(String.valueOf(jPasswordField1.getPassword()).equals("At least 6 digits")){
					jPasswordField1.setEchoChar('*');
					jPasswordField1.setText("");
					jPasswordField1.setForeground(Color.black);
				}
			}
		});
		
		jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel8.setText("\u7c7b\u578b");
		
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"读者", "作者", "管理员"}));


		jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel9.setText("\u6388\u6743\u7801");


		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout.createSequentialGroup().addGap(
										161, 161, 161).addComponent(jButton1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										105,
										javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(163, 163, 163))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				61,
																				61,
																				61)
																		.addComponent(
																				jLabel5)
																		.addGap(
																				24,
																				24,
																				24)
																		.addComponent(
																				jTextField3,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				278,
																				Short.MAX_VALUE))
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				10,
																				10,
																				10)
																		.addComponent(
																				jLabel2))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				64,
																				64,
																				64)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel8)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jLabel4))
																		.addGap(
																				24,
																				24,
																				24)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jPasswordField1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								275,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								275,
																								Short.MAX_VALUE)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jComboBox1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												30,
																												30,
																												30)
																										.addComponent(
																												jLabel9)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jTextField2,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												102,
																												Short.MAX_VALUE)))))
										.addGap(46, 46, 46))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(43, 43, 43)
										.addComponent(jLabel6)
										.addGap(24, 24, 24)
										.addComponent(
												jTextField4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												38, Short.MAX_VALUE)
										.addComponent(
												jLabel7,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												116,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(68, 68, 68)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												81,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																37,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3))
										.addGap(21, 21, 21)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jPasswordField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																37,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																28,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel9))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																37,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																jTextField4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																37,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																35,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(23, 23, 23)
										.addComponent(
												jButton1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												44, Short.MAX_VALUE)
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		try
	    {
	        org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
	    }
	    catch(Exception e)
	    {
	        //TODO exception
	    }
		
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new NovelRegister().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	// End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		System.out.println(jTextField2.getText().getClass());
		
		if(jTextField2.getText().equals("2")){
			System.out.println("right");
		}
		else{
			System.out.println("fail the text is"+jTextField2.getText());
		}
		String email_pattern = "^([a-z0-9A-Z]+[-|\\.]?)+[a-z0-9A-Z]@([a-z0-9A-Z]+(-[a-z0-9A-Z]+)?\\.)+[a-zA-Z]{2,}$";
		boolean isEmail = Pattern.matches(email_pattern, jTextField1.getText());
		
		String psw_pattern = "^[a-zA-Z0-9]{6,20}$";
		boolean isPsw = Pattern.matches(psw_pattern, String.valueOf(jPasswordField1.getPassword()));
		
		if(isEmail){
			System.out.println("邮箱ok");
			if(isPsw){
				System.out.println("密码ok");
				if(jTextField3.getText().length()>0&&jTextField3.getText().length()<=10){
					System.out.println("昵称Ok");
					if(jTextField4.getText().equals(jLabel7.getText().replaceAll(" ", ""))){
						if(!hadregistered(jTextField1.getText())){
							if(jComboBox1.getSelectedItem()=="读者"){
								User u = new User(jTextField1.getText(),String.valueOf(jPasswordField1.getPassword()));
								u.register(jTextField1.getText(), String.valueOf(jPasswordField1.getPassword()), jTextField3.getText(), "0");
								JOptionPane.showMessageDialog(null, "注册成功","提示", JOptionPane.PLAIN_MESSAGE);
								dispose();
								new NovelLogin().setVisible(true);
							}
							else if((jComboBox1.getSelectedItem()=="管理员"&&jTextField2.getText().equals("2"))||(jComboBox1.getSelectedItem()=="作者"&&jTextField2.getText().equals("1"))){
								register(jTextField1.getText(), String.valueOf(jPasswordField1.getPassword()), jTextField3.getText(),jTextField2.getText());
								JOptionPane.showMessageDialog(null, "注册成功","提示", JOptionPane.PLAIN_MESSAGE);
								dispose();
								new NovelLogin().setVisible(true);
							}
							else{
								JOptionPane.showMessageDialog(null, "注册失败");
							}
						}
						else{
							JOptionPane.showMessageDialog(this, "用户已存在");
							dispose();
							new NovelLogin().setVisible(true);
						}
						
					}
					else{
						JOptionPane.showMessageDialog(this, "验证码输入错误");
					}
				}
				else{
					JOptionPane.showMessageDialog(this, "昵称不符合规范(0-10位)");
				}
			}
			else{
				JOptionPane.showMessageDialog(this, "密码不符合规范(6-20位)");
			}
		}
		else{
			JOptionPane.showMessageDialog(this,"邮箱格式错误");
		}
		
	}
	public void register(String account,String password,String nickname,String status){
		@SuppressWarnings("unused")
		String JDBC_DRIVER = "com.mysql.jdbc.Driver";
		String DB_URL = "jdbc:mysql://localhost:3306/hello?useUnicode=true&characterEncoding=utf-8";
		String USER = "root";
		String PASSWORD = "19990428";
		String sql = "insert into `test`(`account`,`password`,`nickname`,`is`)values(?,?,?,?)";
		Connection conn = null;
		PreparedStatement stmt = null;
		try{
			Class.forName("com.mysql.jdbc.Driver");
			conn = DriverManager.getConnection(DB_URL, USER, PASSWORD);
			stmt = (PreparedStatement) conn.prepareStatement(sql);
			stmt.setString(1, account);
			stmt.setString(2, password);
			stmt.setString(3, nickname);
			stmt.setString(4, status);
			stmt.executeUpdate();
			System.out.println("连接使用数据库成功");
			conn.close();
			stmt.close();
			
			} catch (ClassNotFoundException e) {  
			System.out.println("发生错误");  
//            e.printStackTrace();  
			} catch(SQLException e) {
				e.printStackTrace();  
			} 
		}
	public boolean hadregistered(String account){
		@SuppressWarnings("unused")
		String JDBC_DRIVER = "com.mysql.jdbc.Driver";
		String DB_URL = "jdbc:mysql://localhost:3306/hello?useUnicode=true&characterEncoding=utf-8";
		String USER = "root";
		String PASSWORD = "19990428";
		String sql = "select * from `test` where account = ?";
		Connection conn = null;
		PreparedStatement stmt = null;
		try{
			Class.forName("com.mysql.jdbc.Driver");
//			System.out.println("����������ݿ�...");
			conn = DriverManager.getConnection(DB_URL, USER, PASSWORD);
//			System.out.println("ʵ��statement����...");
			stmt = (PreparedStatement) conn.prepareStatement(sql);
			stmt.setString(1, account);
			ResultSet rs = (ResultSet) stmt.executeQuery();
			if(rs.next()){
				return true;
			}
			conn.close();
			stmt.close();
			} catch (ClassNotFoundException e) {  
			System.out.println("ClassNotFoundY异常");  
//            e.printStackTrace();  
			} catch(SQLException e) {
				System.out.println("SQL异常");  
//				e.printStackTrace();  
			}
		return false;
	}
}