/*
 * personalspace.java
 *
 * Created on __DATE__, __TIME__
 */

package novel;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.color.ColorSpace;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.IOException;
import java.security.Signature;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * 
 * @author __USER__
 */
public class personalspace extends javax.swing.JFrame {

	String glo_nickname = null;
	static String nickname = null;
	String account = null;
	String sign = null;
	String facesrc = null;

	/** Creates new form personalspace */
	public personalspace(String nickname) {
		this.nickname = nickname;
		initComponents(nickname);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents(final String nickname) {

		this.setTitle("个人中心");
		jPanel1 = new javax.swing.JPanel();
		jButton4 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jPanel2 = new javax.swing.JPanel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel3 = new javax.swing.JPanel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jLabel21 = new javax.swing.JLabel();
		jLabel22 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jPanel5 = new javax.swing.JPanel();
		jLabel14 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		jButton3 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		// jButton4.setText("暂无头像"); //头像
		try {
			if (haveImg(nickname) == null) {
				this.jButton4.setText("暂无头像");
			} else {
				Image i = new ImageIcon(haveImg(nickname)).getImage()
						.getScaledInstance(144, 128, Image.SCALE_SMOOTH);
				jButton4.setIcon(new ImageIcon(i));
			}
		} catch (SQLException e1) {
			e1.printStackTrace();
		}
		String sql = "select * from test where nickname='" + nickname + "'";
		String signature = null;
		String account = null;
		try {
			ResultSet rs = DB_Connect.getStatement().executeQuery(sql);
			while (rs.next()) {
				signature = rs.getString(8);
				account = rs.getString(2);
			}
		} catch (SQLException e1) {
			e1.printStackTrace();
		}
		if (signature == null) {
			jTextArea1.setText("");
		} else {
			jTextArea1.setText(signature);
		}

		Image img0 = new ImageIcon("src\\img\\baocuntx.jpg").getImage()
				.getScaledInstance(jButton1.getWidth() + 17,
						jButton1.getHeight() + 17, Image.SCALE_SMOOTH);
		jButton1.setIcon(new ImageIcon(img0));
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				int id = 0;
				String new_name = "";
				
					new_name = JOptionPane.showInputDialog("请输入新的昵称:");
					if (new_name == null || new_name.equals("") )
	                 {
	                     return;
	                 }
				
				if (new_name.replaceAll(" ", "").equals("")) {
					JOptionPane.showMessageDialog(null, "新昵称不能为空！");
					return;
				} else {
					String query = "select * from test";
					ResultSet rs;
					try {
						rs = DB_Connect.getStatement().executeQuery(query);
						while (rs.next()) {
							id = Integer.parseInt(rs.getString(1));

						}
					} catch (SQLException e2) {
						e2.printStackTrace();
					}

					String sql = "update test set nickname='" + new_name
							+ "' where id=" + id + "";
					String sql1 = "update like_book set user_id='" + new_name
							+ "' where user_id='" + nickname + "'";
					String sql2 = "update comment set user='" + new_name
							+ "' where user='" + nickname + "'";
					String sql3 = "update book_payment set user_id='"
							+ new_name + "' where user_id='" + nickname + "'";
					String sql4 = "update sharing set user='" + new_name
							+ "' where user='" + nickname + "'";
					String sql5 = "update sharing set to_user='" + new_name
							+ "' where to_user='" + nickname + "'";
					try {
						DB_Connect.getStatement().executeUpdate(sql);
						DB_Connect.getStatement().executeUpdate(sql1);
						DB_Connect.getStatement().executeUpdate(sql2);
						DB_Connect.getStatement().executeUpdate(sql3);
						DB_Connect.getStatement().executeUpdate(sql4);
						DB_Connect.getStatement().executeUpdate(sql5);
						JOptionPane.showMessageDialog(null, "更改成功，请等待资料的上传...");
						glo_nickname = new_name;
					} catch (SQLException e1) {
						JOptionPane.showMessageDialog(null, "更改失败,该用户已存在");
						// e1.printStackTrace();
						return;
					}
				}
			}

		});
		jButton4.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				dispose();
				if (glo_nickname == null) {
					new SelectBooks(nickname).setVisible(true);
				} else {
					new SelectBooks(glo_nickname).setVisible(true);
				}
			}
		});
		jButton4.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
			}

			public void mousePressed(MouseEvent e) {
			}

			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
			}

			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
			}

			public void mouseClicked(MouseEvent e) {
			}
		});

		Image img2 = new ImageIcon("src\\img\\9.9.jpg").getImage()
				.getScaledInstance(jLabel15.getWidth() + 140,
						jLabel15.getHeight() + 140, Image.SCALE_SMOOTH);
		jLabel15.setIcon(new ImageIcon(img2));

		Image img3 = new ImageIcon("src\\img\\10.10.jpg").getImage()
				.getScaledInstance(jLabel16.getWidth() + 140,
						jLabel16.getHeight() + 140, Image.SCALE_SMOOTH);
		jLabel16.setIcon(new ImageIcon(img3));

		Image img4 = new ImageIcon("src\\img\\11.11.jpg").getImage()
				.getScaledInstance(jLabel17.getWidth() + 140,
						jLabel17.getHeight() + 140, Image.SCALE_SMOOTH);
		jLabel17.setIcon(new ImageIcon(img4));

		Image img5 = new ImageIcon("src\\img\\12.12.jpg").getImage()
				.getScaledInstance(jLabel18.getWidth() + 140,
						jLabel18.getHeight() + 140, Image.SCALE_SMOOTH);
		jLabel18.setIcon(new ImageIcon(img5));

		Image img6 = new ImageIcon("src\\img\\13.13.jpg").getImage()
				.getScaledInstance(jLabel19.getWidth() + 140,
						jLabel19.getHeight() + 140, Image.SCALE_SMOOTH);
		jLabel19.setIcon(new ImageIcon(img6));

		Image img7 = new ImageIcon("src\\img\\19.19.jpg").getImage()
				.getScaledInstance(jLabel20.getWidth() + 140,
						jLabel20.getHeight() + 140, Image.SCALE_SMOOTH);
		jLabel20.setIcon(new ImageIcon(img7));

		Image img8 = new ImageIcon("src\\img\\zztx.jpg").getImage()
				.getScaledInstance(jLabel21.getWidth() + 140,
						jLabel21.getHeight() + 140, Image.SCALE_SMOOTH);
		jLabel21.setIcon(new ImageIcon(img8));

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel2.setText("\u6635\u79f0\uff1a");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel3.setText("\u8d26\u53f7\uff1a");

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel4.setText(nickname);

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel5.setText(account);

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel6.setText("\u4e2a\u6027\u7b7e\u540d\uff1a");

		jButton2.setText("\u66f4\u6362\u5934\u50cf");
		jButton2.addActionListener(new ActionListener() {

			File f = null;

			public void actionPerformed(ActionEvent e) {
				JFileChooser jfc = new JFileChooser();
				jfc.showOpenDialog(null);
				f = jfc.getSelectedFile();
				try{
					if (!f.exists()) {
					JOptionPane.showMessageDialog(null, "no exists");
				} else if (!f.getAbsolutePath().endsWith(".jpg")) {
					JOptionPane.showMessageDialog(null, "format is jpg");
				} else {
					Image i = new ImageIcon(f.getAbsolutePath()).getImage()
							.getScaledInstance(144, 128, Image.SCALE_SMOOTH);
					jButton4.setIcon(new ImageIcon(i));
					try {
						Client c = new Client();
						c.uploadFile(f);
						String path = f.getAbsolutePath().replace("\\", "/");
						String sql = "update test set faceSrc = '" + path
								+ "'  where nickname = '" + nickname + "';";
						DB_Connect.getStatement().executeUpdate(sql);
						JOptionPane.showMessageDialog(null, "头像上传成功");
					} catch (SQLException e2) {
						e2.printStackTrace();
					} catch (IOException e3) {
					}

				}
				} catch (Exception e4) {
				}
				
			}
		});

		jTextArea1.setColumns(20);
		jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 15));
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);
		jTextArea1.setLineWrap(true);
		jTextArea1.addMouseListener(new mouseC());

		jLabel10.setText("\u5f20\u4f73\u73ae");

		jLabel11.setText("\u6731\u8c05\u8c05");

		jLabel12.setText("\u9648\u9526\u6167");

		jLabel13.setText("\u6768\u56fd\u534e");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap(27, Short.MAX_VALUE)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabel10,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																92,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel15,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																100,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				89,
																				89,
																				89)
																		.addComponent(
																				jLabel11,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				82,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel3Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel16,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				99,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				90,
																				90,
																				90)
																		.addComponent(
																				jLabel12)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				121,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel13)
																		.addGap(
																				78,
																				78,
																				78))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				70,
																				70,
																				70)
																		.addComponent(
																				jLabel17,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				92,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				73,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel18,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				106,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				38,
																				38,
																				38)))));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				32,
																				32,
																				32)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel18,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								130,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel17,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								130,
																								Short.MAX_VALUE)))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				28,
																				28,
																				28)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel15,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								134,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel16,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								134,
																								Short.MAX_VALUE))))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.CENTER)
																		.addComponent(
																				jLabel13)
																		.addComponent(
																				jLabel11)
																		.addComponent(
																				jLabel12))
														.addComponent(
																jLabel10,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																31,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(54, 54, 54)));

		jTabbedPane1.addTab("\u6211\u6536\u85cf\u7684\u4e66", jPanel3);

		jLabel22.setText("\u4f5c\u5bb6\uff1a\u51b0\u5fc3");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(
																				46,
																				46,
																				46)
																		.addComponent(
																				jLabel21,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				122,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(
																				54,
																				54,
																				54)
																		.addComponent(
																				jLabel22,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				100,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(509, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel4Layout.createSequentialGroup().addGap(35, 35, 35)
						.addComponent(jLabel21,
								javax.swing.GroupLayout.PREFERRED_SIZE, 144,
								javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
								18, 18, 18).addComponent(jLabel22,
								javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(28, Short.MAX_VALUE)));

		jTabbedPane1.addTab("\u6211\u5173\u6ce8\u7684\u4f5c\u8005", jPanel4);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout.createSequentialGroup().addComponent(
						jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
						682, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(28, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290,
				Short.MAX_VALUE));

		jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/czicon.jpg"))); // NOI18N
		jLabel7.setText("\u4f59\u989d\uff1a");

		jLabel8.setText("10.7");

		jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/levelicon.jpg"))); // NOI18N

		jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel14.setText("\u731c\u4f60\u559c\u6b22");

		jLabel15.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
			}

			public void mousePressed(MouseEvent e) {
			}

			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
				jLabel15.setBorder(null);
			}

			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
				jLabel15.setBorder(BorderFactory.createLineBorder(Color.pink));
			}

			public void mouseClicked(MouseEvent e) {
			}
		});
		jLabel16.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
			}

			public void mousePressed(MouseEvent e) {
			}

			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
				jLabel16.setBorder(null);
			}

			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
				jLabel16.setBorder(BorderFactory.createLineBorder(Color.pink));
			}

			public void mouseClicked(MouseEvent e) {
			}
		});
		jLabel17.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
			}

			public void mousePressed(MouseEvent e) {
			}

			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
				jLabel17.setBorder(null);
			}

			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
				jLabel17.setBorder(BorderFactory.createLineBorder(Color.pink));
			}

			public void mouseClicked(MouseEvent e) {
			}
		});
		jLabel18.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
			}

			public void mousePressed(MouseEvent e) {
			}

			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
				jLabel18.setBorder(null);
			}

			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
				jLabel18.setBorder(BorderFactory.createLineBorder(Color.pink));
			}

			public void mouseClicked(MouseEvent e) {
			}
		});
		jLabel19.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
			}

			public void mousePressed(MouseEvent e) {
			}

			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
				jLabel19.setBorder(null);
			}

			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
				jLabel19.setBorder(BorderFactory.createLineBorder(Color.pink));
			}

			public void mouseClicked(MouseEvent e) {
			}
		});
		jLabel20.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
			}

			public void mousePressed(MouseEvent e) {
			}

			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
				jLabel20.setBorder(null);
			}

			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
				jLabel20.setBorder(BorderFactory.createLineBorder(Color.pink));
			}

			public void mouseClicked(MouseEvent e) {
			}
		});

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout
				.setHorizontalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel5Layout
																		.createSequentialGroup()
																		.addGap(
																				30,
																				30,
																				30)
																		.addComponent(
																				jLabel14,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				121,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel5Layout
																		.createSequentialGroup()
																		.addGap(
																				158,
																				158,
																				158)
																		.addComponent(
																				jLabel19,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				117,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				208,
																				208,
																				208)
																		.addComponent(
																				jLabel20,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				117,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(242, Short.MAX_VALUE)));
		jPanel5Layout
				.setVerticalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addComponent(
												jLabel14,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												32,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel20,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																133,
																Short.MAX_VALUE)
														.addComponent(
																jLabel19,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																133,
																Short.MAX_VALUE))
										.addGap(23, 23, 23)));

		jButton3.setText("\u6211\u7684\u4e66\u8bc4");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				58,
																				58,
																				58)
																		.addComponent(
																				jButton4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				146,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				69,
																				69,
																				69)
																		.addComponent(
																				jButton2)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												26, Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				421,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap())
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel2,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												59,
																												Short.MAX_VALUE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel4,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												77,
																												Short.MAX_VALUE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												jButton1,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												39,
																												Short.MAX_VALUE)
																										.addGap(
																												142,
																												142,
																												142))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel3)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel5,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												200,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												jLabel9)
																										.addGap(
																												90,
																												90,
																												90)))
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel7)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel8,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												141,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(
																												26,
																												26,
																												26)
																										.addComponent(
																												jButton3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												113,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGap(
																				101,
																				101,
																				101))))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap(115, Short.MAX_VALUE)
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(79, 79, 79)).addGroup(
								jPanel1Layout.createSequentialGroup().addGap(
										30, 30, 30).addComponent(jPanel5,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(32, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(59, 59, 59)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				130,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jButton2,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				34,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.CENTER)
																						.addComponent(
																								jLabel4,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								29,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								29,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								29,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								jLabel8))
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(
																												30,
																												30,
																												30)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.CENTER)
																														.addComponent(
																																jLabel3)
																														.addComponent(
																																jLabel5,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																21,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																jLabel9)))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												jButton3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												38,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGap(
																				2,
																				2,
																				2)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(
																												24,
																												24,
																												24)
																										.addComponent(
																												jLabel6))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(
																												32,
																												32,
																												32)
																										.addComponent(
																												jScrollPane1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												61,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addGap(32, 32, 32)
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel5,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		try {
			org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
		} catch (Exception e) {
			// TODO exception
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new personalspace(nickname).setVisible(true);
			}
		});
	}

	// 鼠标监听重写
	class mouseC extends MouseAdapter {
		int i = 0;

		public void mouseClicked(MouseEvent arg0) {
			if (arg0.getButton() == MouseEvent.BUTTON1) {
				// 左键点击
				i++;
				String sign1 = jTextArea1.getText();
				if (sign1.length() < 10) {
					if (i < 2) {
						JOptionPane.showMessageDialog(null, "左键编辑，右键保存");
					}
				} else {
					int selected1 = JOptionPane.showConfirmDialog(null,
							"是否删除个性签名", "请选择", JOptionPane.YES_NO_OPTION);
					if (selected1 == 0) {
						jTextArea1.setText("");
					} else {
						return;
					}
				}
			} else if (arg0.getButton() == MouseEvent.BUTTON3) {
				// 右键点击
				String sign2 = jTextArea1.getText();
				int selected2 = JOptionPane.showConfirmDialog(null,
						"确认保存个性签名吗", "请确认", JOptionPane.YES_NO_OPTION);
				if (selected2 == 0) {
					String sql = "update test set sign='" + sign2
							+ "' where nickname='" + nickname + "'";
					try {
						DB_Connect.getStatement().executeUpdate(sql);
						JOptionPane.showMessageDialog(null, "保存成功！");
					} catch (SQLException e) {
						JOptionPane.showMessageDialog(null, "保存失败!");
						e.printStackTrace();
					}
				}
			}
		}
	}

	public String haveImg(String nickname) throws SQLException {
		String sql = "select * from test where nickname = '" + nickname + "';";
		ResultSet rs = DB_Connect.getStatement().executeQuery(sql);
		while (rs.next()) {
			String adress = rs.getString(7);
			if (adress != null) {
				return adress;
			}
		}
		return null;
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextArea jTextArea1;
	// End of variables declaration//GEN-END:variables

}