/*
 * SelectBooks.java
 *
 * Created on __DATE__, __TIME__
 */

package novel;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  __USER__
 */
public class SelectBooks extends javax.swing.JFrame{

	/** Creates new form SelectBooks */
	static String nickname = null;
	public SelectBooks(String nickname) {
		this.nickname = nickname;
		initComponents(nickname);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
//GEN-BEGIN:initComponents
// <editor-fold defaultstate="collapsed" desc="Generated Code">
		private void initComponents(final String nickname){

			final JFrame jFrame1 = new javax.swing.JFrame();
			this.setResizable(false);
		this.setTitle("选择书籍");
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		jButton13 = new javax.swing.JButton();
		jButton14 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jPanel2.setBackground(new java.awt.Color(245, 246, 241));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/icon4.jpg"))); // NOI18N

		jTextField1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jTextField1.setText("书名、作者、ISBN");
		jTextField1.setForeground(Color.gray);
		jTextField1.addFocusListener(new FocusListener() {
			
			@Override
			public void focusLost(FocusEvent e) {
				// TODO Auto-generated method stub
				if(jTextField1.getText().equals("")){
					jTextField1.setText("书名、作者、ISBN");
					jTextField1.setForeground(Color.gray);
				}
			}
			
			@Override
			public void focusGained(FocusEvent e) {
				// TODO Auto-generated method stub
				if(jTextField1.getText().equals("书名、作者、ISBN")){
					jTextField1.setText("");
					jTextField1.setForeground(Color.black);
				}
			}
		});

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/icon5.png"))); // NOI18N
		jLabel2.addMouseListener(new MouseListener()  {
			Color c = new Color(166,165,155);
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				jLabel2.setBackground(c);
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				jLabel2.setBackground(new Color(156,155,145));
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				setCursor(Cursor.getDefaultCursor());
				jLabel2.setBackground(null);
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
				jLabel2.setOpaque(true);
				jLabel2.setBackground(c);
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				String content = jTextField1.getText();
				String site = "https://www.baidu.com/s?wd="+content;
				try {
					Desktop desktop = Desktop.getDesktop();
					if (desktop.isDesktopSupported()
							&& desktop.isSupported(Desktop.Action.BROWSE)) {
						URI uri = new URI(site);
						desktop.browse(uri);
					}
				} catch (IOException ex) {
					System.out.println(ex);
				} catch (URISyntaxException ex) {
					System.out.println(ex);
				}

			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												54, Short.MAX_VALUE)
										.addComponent(
												jTextField1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												543,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(66, 66, 66)
										.addComponent(
												jLabel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												58,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(63, 63, 63)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(16, 16, 16)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				67,
																				Short.MAX_VALUE)
																		.addContainerGap(
																				28,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				8,
																				8,
																				8)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								56,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				31,
																				31,
																				31)))));

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));
		jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(
				javax.swing.border.BevelBorder.RAISED));

		jLabel3.setFont(new java.awt.Font("黑体", 1, 25));
		jLabel3.setText("\u65b0\u4e66\u901f\u9012");

		jButton11.setText("\u516c\u544a");
		jButton11.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				new Notice_view().setVisible(true);
			}
		});

		jButton12.setText("\u5c0f\u8bf4\u6392\u884c");
		jButton12.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				new List().setVisible(true);
			}
		});

		jButton13.setText("\u4e2a\u4eba\u7a7a\u95f4");
		jButton13.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (nickname==null) {
					JOptionPane.showMessageDialog(null, "请先进行登陆");
					new NovelLogin().setVisible(true);
					dispose();
					return;
				}
				new personalspace(nickname).setVisible(true);
				dispose();
			}
		});

		jButton14.setText("\u65e5\u63a8");
		jButton14.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				new Recommend_view().setVisible(true);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												347, Short.MAX_VALUE)
										.addComponent(jButton14).addGap(40, 40,
												40).addComponent(jButton11)
										.addGap(43, 43, 43).addComponent(
												jButton12).addGap(43, 43, 43)
										.addComponent(jButton13).addGap(29, 29,
												29)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jButton11)
																		.addComponent(
																				jButton12)
																		.addComponent(
																				jButton13)
																		.addComponent(
																				jButton14))
														.addComponent(jLabel3))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));

		
		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				109,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				92,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				109,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				109,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				92,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				109,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(90, 90, 90)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jButton5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																109,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																109,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(90, 90, 90)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jButton3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																109,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton9,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																109,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(92, 92, 92)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jButton4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																109,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton10,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																109,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																138,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																138,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																138,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																138,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																138,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(37, 37, 37)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																138,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																138,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																138,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton9,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																138,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton10,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																138,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(41, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												jPanel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel4,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		
		pack();
		
		jButton1.setText("jButton1");
		Image img0 = new ImageIcon("src\\img\\0.jpg").getImage().getScaledInstance
		(jButton1.getWidth()+11, jButton1.getHeight(), Image.SCALE_SMOOTH);
		jButton1.setIcon(new ImageIcon(img0));
		jButton1.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
				
			}
			public void mousePressed(MouseEvent e){
				dispose();
				String bookname = getline("src\\infos\\0.txt").get(0);
				BookIntroduce b1 = new BookIntroduce(nickname,bookname,1);
				b1.setVisible(true);
				b1.jTextArea1.setText(gettxt("src\\content\\0.txt"));
				Image img0 = new ImageIcon("src\\img\\0.jpg").getImage().getScaledInstance
				(b1.jLabel2.getWidth(), b1.jLabel2.getHeight(), Image.SCALE_SMOOTH);
				b1.jLabel2.setIcon(new ImageIcon(img0));
				b1.jLabel1.setText(getline("src\\infos\\0.txt").get(0));    //书名
				b1.jLabel13.setText(getline("src\\infos\\0.txt").get(1));   //作者
				b1.jLabel14.setText(getline("src\\infos\\0.txt").get(2));   //出版社
				b1.jLabel15.setText(getline("src\\infos\\0.txt").get(3));   //原作名
				b1.jLabel16.setText("暂不了解");                             //译者
				b1.jLabel17.setText(getline("src\\infos\\0.txt").get(4));   //出版年
				b1.jLabel18.setText(getline("src\\infos\\0.txt").get(5));   //页数
				b1.jLabel19.setText("暂不了解");                             //定价
				b1.jLabel20.setText(getline("src\\infos\\0.txt").get(6));   //丛书
				b1.jLabel21.setText(getline("src\\infos\\0.txt").get(8));   //ISBN
			}
			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
			}
			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
			}
			public void mouseClicked(MouseEvent e) {
				
			}
		});
		
		jButton2.setText("jButton1");
		Image img1 = new ImageIcon("src\\img\\1.jpg").getImage().getScaledInstance
		(jButton2.getWidth()+11, jButton2.getHeight(), Image.SCALE_SMOOTH);
		jButton2.setIcon(new ImageIcon(img1));
		jButton2.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
				
			}
			public void mousePressed(MouseEvent e) {
				dispose();
				String bookname = getline("src\\infos\\1.txt").get(0);
				BookIntroduce b1 = new BookIntroduce(nickname,bookname,2);
				b1.setVisible(true);
				b1.jTextArea1.setText(gettxt("src\\content\\1.txt"));
				Image img0 = new ImageIcon("src\\img\\1.jpg").getImage().getScaledInstance
				(b1.jLabel2.getWidth(), b1.jLabel2.getHeight(), Image.SCALE_SMOOTH);
				b1.jLabel2.setIcon(new ImageIcon(img0));
				b1.jLabel1.setText(getline("src\\infos\\1.txt").get(0));
				
				b1.jLabel13.setText(getline("src\\infos\\1.txt").get(1));
				b1.jLabel14.setText(getline("src\\infos\\1.txt").get(2));
				b1.jLabel15.setText("暂不了解");
				b1.jLabel16.setText("暂不了解");
				b1.jLabel17.setText(getline("src\\infos\\1.txt").get(3));
				b1.jLabel18.setText(getline("src\\infos\\1.txt").get(4));
				b1.jLabel19.setText("暂不了解");
				b1.jLabel20.setText(getline("src\\infos\\1.txt").get(5));
				b1.jLabel21.setText(getline("src\\infos\\1.txt").get(6));
			}
			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
			}
			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
			}
			public void mouseClicked(MouseEvent e) {
				
			}
		});
		
		jButton3.setText("jButton1");
		Image img2 = new ImageIcon("src\\img\\2.jpg").getImage().getScaledInstance
		(jButton3.getWidth()+11, jButton3.getHeight(), Image.SCALE_SMOOTH);
		jButton3.setIcon(new ImageIcon(img2));
		jButton3.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
				
			}
			public void mousePressed(MouseEvent e) {
				dispose();
				String bookname = getline("src\\infos\\2.txt").get(0);
				BookIntroduce b1 = new BookIntroduce(nickname,bookname,3);
				
				b1.setVisible(true);
				b1.jTextArea1.setText(gettxt("src\\content\\2.txt"));
				Image img0 = new ImageIcon("src\\img\\2.jpg").getImage().getScaledInstance
				(b1.jLabel2.getWidth(), b1.jLabel2.getHeight(), Image.SCALE_SMOOTH);
				b1.jLabel2.setIcon(new ImageIcon(img0));
				b1.jLabel1.setText(getline("src\\infos\\2.txt").get(0));
				
				b1.jLabel13.setText(getline("src\\infos\\2.txt").get(1));
				b1.jLabel14.setText(getline("src\\infos\\2.txt").get(2));
				b1.jLabel15.setText(getline("src\\infos\\2.txt").get(3));
				b1.jLabel16.setText("暂不了解");
				b1.jLabel17.setText(getline("src\\infos\\2.txt").get(4));
				b1.jLabel18.setText(getline("src\\infos\\2.txt").get(5));
				b1.jLabel19.setText("暂不了解");
				b1.jLabel20.setText(getline("src\\infos\\2.txt").get(6));
				b1.jLabel21.setText(getline("src\\infos\\2.txt").get(8));
			}
			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
			}
			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
			}
			public void mouseClicked(MouseEvent e) {
				
			}
		});
		
		jButton4.setText("jButton1");
		Image img3 = new ImageIcon("src\\img\\3.jpg").getImage().getScaledInstance
		(jButton4.getWidth()+11, jButton4.getHeight(), Image.SCALE_SMOOTH);
		jButton4.setIcon(new ImageIcon(img3));
		jButton4.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
				
			}
			public void mousePressed(MouseEvent e) {
				dispose();
				String bookname = getline("src\\infos\\3.txt").get(0);
				BookIntroduce b1 = new BookIntroduce(nickname,bookname,4);
				
				b1.setVisible(true);
				b1.jTextArea1.setText(gettxt("src\\content\\3.txt"));
				Image img0 = new ImageIcon("src\\img\\3.jpg").getImage().getScaledInstance
				(b1.jLabel2.getWidth(), b1.jLabel2.getHeight(), Image.SCALE_SMOOTH);
				b1.jLabel2.setIcon(new ImageIcon(img0));
//				b1.jLabel1.setText(getline("src\\infos\\3.txt").get(0));
				
				b1.jLabel13.setText(getline("src\\infos\\3.txt").get(1));
				b1.jLabel14.setText(getline("src\\infos\\3.txt").get(2));
				b1.jLabel15.setText("暂不了解");
				b1.jLabel16.setText("暂不了解");
				b1.jLabel17.setText(getline("src\\infos\\3.txt").get(3));
				b1.jLabel18.setText(getline("src\\infos\\3.txt").get(4));
				b1.jLabel19.setText("暂不了解");
				b1.jLabel20.setText(getline("src\\infos\\3.txt").get(5));
				b1.jLabel21.setText(getline("src\\infos\\3.txt").get(7));
			}
			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
			}
			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
			}
			public void mouseClicked(MouseEvent e) {
				
			}
		});
	
		jButton5.setText("jButton1");
		Image img4 = new ImageIcon("src\\img\\4.jpg").getImage().getScaledInstance
		(jButton5.getWidth()+11, jButton5.getHeight(), Image.SCALE_SMOOTH);
		jButton5.setIcon(new ImageIcon(img4));
		jButton5.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
				
			}
			public void mousePressed(MouseEvent e) {
				dispose();
				String bookname = getline("src\\infos\\4.txt").get(0);
				BookIntroduce b1 = new BookIntroduce(nickname,bookname,5);
				
				b1.setVisible(true);
				b1.jTextArea1.setText(gettxt("src\\content\\4.txt"));
				Image img0 = new ImageIcon("src\\img\\4.jpg").getImage().getScaledInstance
				(b1.jLabel2.getWidth(), b1.jLabel2.getHeight(), Image.SCALE_SMOOTH);
				b1.jLabel2.setIcon(new ImageIcon(img0));
				b1.jLabel1.setText(getline("src\\infos\\4.txt").get(0));
				
				b1.jLabel13.setText(getline("src\\infos\\4.txt").get(1));
				b1.jLabel14.setText(getline("src\\infos\\4.txt").get(2));
				b1.jLabel15.setText("暂不了解");
				b1.jLabel16.setText("暂不了解");
				b1.jLabel17.setText(getline("src\\infos\\4.txt").get(3));
				b1.jLabel18.setText(getline("src\\infos\\4.txt").get(4));
				b1.jLabel19.setText("暂不了解");
				b1.jLabel20.setText(getline("src\\infos\\4.txt").get(5));
				b1.jLabel21.setText(getline("src\\infos\\4.txt").get(7));
			}
			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
			}
			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
			}
			public void mouseClicked(MouseEvent e) {
				
			}
		});

		jButton6.setText("jButton1");
		Image img5 = new ImageIcon("src\\img\\5.jpg").getImage().getScaledInstance
		(jButton6.getWidth()+11, jButton6.getHeight(), Image.SCALE_SMOOTH);
		jButton6.setIcon(new ImageIcon(img5));
		jButton6.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
				
			}
			public void mousePressed(MouseEvent e) {
				dispose();
				String bookname = getline("src\\infos\\5.txt").get(0);
				BookIntroduce b1 = new BookIntroduce(nickname,bookname,6);
				
				b1.setVisible(true);
				b1.jTextArea1.setText(gettxt("src\\content\\5.txt"));
				Image img0 = new ImageIcon("src\\img\\5.jpg").getImage().getScaledInstance
				(b1.jLabel2.getWidth(), b1.jLabel2.getHeight(), Image.SCALE_SMOOTH);
				b1.jLabel2.setIcon(new ImageIcon(img0));
				b1.jLabel1.setText(getline("src\\infos\\5.txt").get(0));
				
				b1.jLabel13.setText(getline("src\\infos\\5.txt").get(1));
				b1.jLabel14.setText(getline("src\\infos\\5.txt").get(2));
				b1.jLabel15.setText(getline("src\\infos\\5.txt").get(3));
				b1.jLabel16.setText("暂不了解");
				b1.jLabel17.setText(getline("src\\infos\\5.txt").get(4));
				b1.jLabel18.setText(getline("src\\infos\\5.txt").get(5));
				b1.jLabel19.setText("暂不了解");
				b1.jLabel20.setText(getline("src\\infos\\5.txt").get(6));
				b1.jLabel21.setText(getline("src\\infos\\5.txt").get(8));
			}
			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
			}
			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
			}
			public void mouseClicked(MouseEvent e) {
				
			}
		});

		jButton7.setText("jButton1");
		Image img6 = new ImageIcon("src\\img\\6.jpg").getImage().getScaledInstance
		(jButton7.getWidth()+11, jButton7.getHeight(), Image.SCALE_SMOOTH);
		jButton7.setIcon(new ImageIcon(img6));
		jButton7.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
				
			}
			public void mousePressed(MouseEvent e) {
				dispose();
				String bookname = getline("src\\infos\\6.txt").get(0);
				BookIntroduce b1 = new BookIntroduce(nickname,bookname,7);
				
				b1.setVisible(true);
				b1.jTextArea1.setText(gettxt("src\\content\\6.txt"));
				Image img0 = new ImageIcon("src\\img\\6.jpg").getImage().getScaledInstance
				(b1.jLabel2.getWidth(), b1.jLabel2.getHeight(), Image.SCALE_SMOOTH);
				b1.jLabel2.setIcon(new ImageIcon(img0));
//				b1.jLabel1.setText(getline("src\\infos\\6.txt").get(0));
			
				b1.jLabel13.setText(getline("src\\infos\\6.txt").get(1));
				b1.jLabel14.setText(getline("src\\infos\\6.txt").get(2));
				b1.jLabel15.setText(getline("src\\infos\\6.txt").get(3));
				b1.jLabel16.setText("暂不了解");
				b1.jLabel17.setText(getline("src\\infos\\6.txt").get(5));
				b1.jLabel18.setText(getline("src\\infos\\6.txt").get(6));
				b1.jLabel19.setText("暂不了解");
				b1.jLabel20.setText(getline("src\\infos\\6.txt").get(7));
				b1.jLabel21.setText(getline("src\\infos\\6.txt").get(9));
			}
			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
			}
			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
			}
			public void mouseClicked(MouseEvent e) {
				
			}
		});

		jButton8.setText("jButton1");
		Image img7 = new ImageIcon("src\\img\\7.jpg").getImage().getScaledInstance
		(jButton8.getWidth()+11, jButton8.getHeight(), Image.SCALE_SMOOTH);
		jButton8.setIcon(new ImageIcon(img7));
		jButton8.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
				
			}
			public void mousePressed(MouseEvent e) {
				dispose();
				String bookname = getline("src\\infos\\7.txt").get(0);
				BookIntroduce b1 = new BookIntroduce(nickname,bookname,8);
				
				b1.setVisible(true);
				b1.jTextArea1.setText(gettxt("src\\content\\7.txt"));
				Image img0 = new ImageIcon("src\\img\\7.jpg").getImage().getScaledInstance
				(b1.jLabel2.getWidth(), b1.jLabel2.getHeight(), Image.SCALE_SMOOTH);
				b1.jLabel2.setIcon(new ImageIcon(img0));
				b1.jLabel1.setText(getline("src\\infos\\7.txt").get(0));
				
				b1.jLabel13.setText(getline("src\\infos\\7.txt").get(1));
				b1.jLabel14.setText(getline("src\\infos\\7.txt").get(2));
				b1.jLabel15.setText(getline("src\\infos\\7.txt").get(3));
				b1.jLabel16.setText("暂不了解");
				b1.jLabel17.setText(getline("src\\infos\\7.txt").get(4));
				b1.jLabel18.setText(getline("src\\infos\\7.txt").get(5));
				b1.jLabel19.setText("暂不了解");
				b1.jLabel20.setText(getline("src\\infos\\7.txt").get(6));
				b1.jLabel21.setText(getline("src\\infos\\7.txt").get(8));
			}
			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
			}
			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
			}
			public void mouseClicked(MouseEvent e) {
				
			}
		});

		jButton9.setText("jButton1");
		Image img8 = new ImageIcon("src\\img\\8.jpg").getImage().getScaledInstance
		(jButton9.getWidth()+11, jButton9.getHeight(), Image.SCALE_SMOOTH);
		jButton9.setIcon(new ImageIcon(img8));
		jButton9.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
				
			}
			public void mousePressed(MouseEvent e) {
				dispose();
				String bookname = getline("src\\infos\\8.txt").get(0);
				BookIntroduce b1 = new BookIntroduce(nickname,bookname,9);
				
				b1.setVisible(true);
				b1.jTextArea1.setText(gettxt("src\\content\\8.txt"));
				Image img0 = new ImageIcon("src\\img\\8.jpg").getImage().getScaledInstance
				(b1.jLabel2.getWidth(), b1.jLabel2.getHeight(), Image.SCALE_SMOOTH);
				b1.jLabel2.setIcon(new ImageIcon(img0));
				b1.jLabel1.setText(getline("src\\infos\\8.txt").get(0));
				
				b1.jLabel13.setText(getline("src\\infos\\8.txt").get(1));
				b1.jLabel14.setText(getline("src\\infos\\8.txt").get(2));
				b1.jLabel15.setText("暂不了解");
				b1.jLabel16.setText("暂不了解");
				b1.jLabel17.setText(getline("src\\infos\\8.txt").get(3));
				b1.jLabel18.setText(getline("src\\infos\\8.txt").get(4));
				b1.jLabel19.setText("暂不了解");
				b1.jLabel20.setText(getline("src\\infos\\8.txt").get(5));
				b1.jLabel21.setText(getline("src\\infos\\8.txt").get(7));
			}
			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
			}
			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
			}
			public void mouseClicked(MouseEvent e) {
				
			}
		});

		jButton10.setText("jButton1");
		Image img9 = new ImageIcon("src\\img\\9.jpg").getImage().getScaledInstance
		(jButton10.getWidth()+11, jButton10.getHeight(), Image.SCALE_SMOOTH);
		jButton10.setIcon(new ImageIcon(img9));
		jButton10.addMouseListener(new MouseListener() {
			public void mouseReleased(MouseEvent e) {
				
			}
			public void mousePressed(MouseEvent e) {
				dispose();
				String bookname = getline("src\\infos\\9.txt").get(0);
				BookIntroduce b1 = new BookIntroduce(nickname,bookname,10);
				
				b1.setVisible(true);
				b1.jTextArea1.setText(gettxt("src\\content\\9.txt"));
				Image img0 = new ImageIcon("src\\img\\9.jpg").getImage().getScaledInstance
				(b1.jLabel2.getWidth(), b1.jLabel2.getHeight(), Image.SCALE_SMOOTH);
				b1.jLabel2.setIcon(new ImageIcon(img0));
				b1.jLabel1.setText(getline("src\\infos\\9.txt").get(0));
				
				b1.jLabel13.setText(getline("src\\infos\\9.txt").get(1)); 
				b1.jLabel14.setText(getline("src\\infos\\9.txt").get(2));
				b1.jLabel15.setText(getline("src\\infos\\9.txt").get(3));
				b1.jLabel16.setText("暂不了解");
				b1.jLabel17.setText(getline("src\\infos\\9.txt").get(4));
				b1.jLabel18.setText(getline("src\\infos\\9.txt").get(5));
				b1.jLabel19.setText("暂不了解");
				b1.jLabel20.setText(getline("src\\infos\\9.txt").get(6));
				b1.jLabel21.setText(getline("src\\infos\\9.txt").get(8));
			}
			public void mouseExited(MouseEvent e) {
				setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
			}
			public void mouseEntered(MouseEvent e) {
				setCursor(new Cursor(Cursor.HAND_CURSOR));
			}
			public void mouseClicked(MouseEvent e) {
				
			}
		});
	}
		/***
		 * 获得文本里的内容
		 * @param url
		 * @return
		 */
		public static String gettxt(String url){
			StringBuilder result = new StringBuilder();
	        try {
//	          BufferedReader bfr = new BufferedReader(new FileReader(new File(filePath)));
	            BufferedReader bfr = new BufferedReader(new InputStreamReader(new FileInputStream(new File(url)), "gbk"));
	            String lineTxt = null;
	            while ((lineTxt = bfr.readLine()) != null) {
	                result.append(lineTxt).append("\n");
	            }
	            bfr.close();
	        } catch (Exception e) {
	            e.printStackTrace();
	        }
	        return result.toString();
	    }
		
		/***
		 * 获得每行数据
		 * @param url
		 * @return
		 */
		public static ArrayList<String> getline(String url){
			ArrayList<String> readList = new ArrayList<String>();  
	        try {
	            BufferedReader bfr = new BufferedReader(new InputStreamReader(new FileInputStream(new File(url)), "gbk"));
	            String lineTxt = null;
	            while ((lineTxt = bfr.readLine()) != null) {
	                readList.add(lineTxt);
	            }
	            bfr.close();
	        } catch (Exception e) {
	            e.printStackTrace();
	            return null;
	        }
	        return readList;
	    }
		
	// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SelectBooks(nickname).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}